# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dcb425a3beb6b3d7331875bf98b28656fb8f436bdb241e992627e7d926e9c689f9f5031daf3e7dfe65fb11ad94052e15f8a7174f98ba356a3900e4e37764046

test:
  secret_key_base: cb6d650cb8643c3863e63b4ba0a0af504cbf857523f6c095c838a795b1d735af5e8ac0d2b0d978294ca11ed4eefc9cddd3341e713fb1b39bcef38ae95241b404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
